// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/press": {
    params: {};
  };
  "/articles": {
    params: {};
  };
  "/articles/:slug": {
    params: {
      "slug": string;
    };
  };
  "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05D7\u05E9\u05D1\u05D5\u05DF-\u05E4\u05D9\u05D9\u05E1\u05D1\u05D5\u05E7": {
    params: {};
  };
  "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05D7\u05E9\u05D1\u05D5\u05DF-\u05D0\u05D9\u05E0\u05E1\u05D8\u05D2\u05E8\u05DD": {
    params: {};
  };
  "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05D7\u05E9\u05D1\u05D5\u05DF-\u05D5\u05D5\u05D0\u05D8\u05E1\u05D0\u05E4": {
    params: {};
  };
  "/\u05D7\u05E9\u05D1\u05D5\u05DF-\u05E4\u05D9\u05D9\u05E1\u05D1\u05D5\u05E7-\u05DE\u05D5\u05E9\u05D1\u05EA": {
    params: {};
  };
  "/\u05D7\u05E9\u05D1\u05D5\u05DF-\u05D0\u05D9\u05E0\u05E1\u05D8\u05D2\u05E8\u05DD-\u05E0\u05E4\u05E8\u05E5": {
    params: {};
  };
  "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05DE\u05E0\u05D4\u05DC-\u05DE\u05D5\u05D3\u05E2\u05D5\u05EA": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/testimonials": {
    params: {};
  };
  "/bms-sm": {
    params: {};
  };
  "/VSL-BMS": {
    params: {};
  };
  "/\u05EA\u05D5\u05D3\u05D4-\u05E7\u05DC\u05D9\u05E1\u05D8": {
    params: {};
  };
  "/\u05EA\u05D5\u05D3\u05D4-\u05E8\u05DB\u05D9\u05E9\u05D4": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/privacy" | "/press" | "/articles" | "/articles/:slug" | "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05D7\u05E9\u05D1\u05D5\u05DF-\u05E4\u05D9\u05D9\u05E1\u05D1\u05D5\u05E7" | "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05D7\u05E9\u05D1\u05D5\u05DF-\u05D0\u05D9\u05E0\u05E1\u05D8\u05D2\u05E8\u05DD" | "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05D7\u05E9\u05D1\u05D5\u05DF-\u05D5\u05D5\u05D0\u05D8\u05E1\u05D0\u05E4" | "/\u05D7\u05E9\u05D1\u05D5\u05DF-\u05E4\u05D9\u05D9\u05E1\u05D1\u05D5\u05E7-\u05DE\u05D5\u05E9\u05D1\u05EA" | "/\u05D7\u05E9\u05D1\u05D5\u05DF-\u05D0\u05D9\u05E0\u05E1\u05D8\u05D2\u05E8\u05DD-\u05E0\u05E4\u05E8\u05E5" | "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05DE\u05E0\u05D4\u05DC-\u05DE\u05D5\u05D3\u05E2\u05D5\u05EA" | "/faq" | "/testimonials" | "/bms-sm" | "/VSL-BMS" | "/\u05EA\u05D5\u05D3\u05D4-\u05E7\u05DC\u05D9\u05E1\u05D8" | "/\u05EA\u05D5\u05D3\u05D4-\u05E8\u05DB\u05D9\u05E9\u05D4" | "/dashboard";
  };
  "./routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/privacy.jsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "./routes/press.jsx": {
    id: "routes/press";
    page: "/press";
  };
  "./routes/articles.jsx": {
    id: "routes/articles";
    page: "/articles";
  };
  "./routes/articles.$slug.jsx": {
    id: "routes/articles.$slug";
    page: "/articles/:slug";
  };
  "./routes/facebook-recovery.jsx": {
    id: "routes/facebook-recovery";
    page: "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05D7\u05E9\u05D1\u05D5\u05DF-\u05E4\u05D9\u05D9\u05E1\u05D1\u05D5\u05E7";
  };
  "./routes/instagram-recovery.jsx": {
    id: "routes/instagram-recovery";
    page: "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05D7\u05E9\u05D1\u05D5\u05DF-\u05D0\u05D9\u05E0\u05E1\u05D8\u05D2\u05E8\u05DD";
  };
  "./routes/whatsapp-recovery.jsx": {
    id: "routes/whatsapp-recovery";
    page: "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05D7\u05E9\u05D1\u05D5\u05DF-\u05D5\u05D5\u05D0\u05D8\u05E1\u05D0\u05E4";
  };
  "./routes/facebook-disabled.jsx": {
    id: "routes/facebook-disabled";
    page: "/\u05D7\u05E9\u05D1\u05D5\u05DF-\u05E4\u05D9\u05D9\u05E1\u05D1\u05D5\u05E7-\u05DE\u05D5\u05E9\u05D1\u05EA";
  };
  "./routes/instagram-hacked.jsx": {
    id: "routes/instagram-hacked";
    page: "/\u05D7\u05E9\u05D1\u05D5\u05DF-\u05D0\u05D9\u05E0\u05E1\u05D8\u05D2\u05E8\u05DD-\u05E0\u05E4\u05E8\u05E5";
  };
  "./routes/ads-manager.jsx": {
    id: "routes/ads-manager";
    page: "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05DE\u05E0\u05D4\u05DC-\u05DE\u05D5\u05D3\u05E2\u05D5\u05EA";
  };
  "./routes/faq.jsx": {
    id: "routes/faq";
    page: "/faq";
  };
  "./routes/testimonials.jsx": {
    id: "routes/testimonials";
    page: "/testimonials";
  };
  "./routes/bms-sm.jsx": {
    id: "routes/bms-sm";
    page: "/bms-sm";
  };
  "./routes/vsl-bms.jsx": {
    id: "routes/vsl-bms";
    page: "/VSL-BMS";
  };
  "./routes/thank-you-lead.jsx": {
    id: "routes/thank-you-lead";
    page: "/\u05EA\u05D5\u05D3\u05D4-\u05E7\u05DC\u05D9\u05E1\u05D8";
  };
  "./routes/thank-you-purchase.jsx": {
    id: "routes/thank-you-purchase";
    page: "/\u05EA\u05D5\u05D3\u05D4-\u05E8\u05DB\u05D9\u05E9\u05D4";
  };
  "./routes/dashboard.jsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/home": typeof import("./app/./routes/home.jsx");
  "routes/privacy": typeof import("./app/./routes/privacy.jsx");
  "routes/press": typeof import("./app/./routes/press.jsx");
  "routes/articles": typeof import("./app/./routes/articles.jsx");
  "routes/articles.$slug": typeof import("./app/./routes/articles.$slug.jsx");
  "routes/facebook-recovery": typeof import("./app/./routes/facebook-recovery.jsx");
  "routes/instagram-recovery": typeof import("./app/./routes/instagram-recovery.jsx");
  "routes/whatsapp-recovery": typeof import("./app/./routes/whatsapp-recovery.jsx");
  "routes/facebook-disabled": typeof import("./app/./routes/facebook-disabled.jsx");
  "routes/instagram-hacked": typeof import("./app/./routes/instagram-hacked.jsx");
  "routes/ads-manager": typeof import("./app/./routes/ads-manager.jsx");
  "routes/faq": typeof import("./app/./routes/faq.jsx");
  "routes/testimonials": typeof import("./app/./routes/testimonials.jsx");
  "routes/bms-sm": typeof import("./app/./routes/bms-sm.jsx");
  "routes/vsl-bms": typeof import("./app/./routes/vsl-bms.jsx");
  "routes/thank-you-lead": typeof import("./app/./routes/thank-you-lead.jsx");
  "routes/thank-you-purchase": typeof import("./app/./routes/thank-you-purchase.jsx");
  "routes/dashboard": typeof import("./app/./routes/dashboard.jsx");
};