// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/press": {
    params: {};
  };
  "/articles": {
    params: {};
  };
  "/articles/:slug": {
    params: {
      "slug": string;
    };
  };
  "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05D7\u05E9\u05D1\u05D5\u05DF-\u05E4\u05D9\u05D9\u05E1\u05D1\u05D5\u05E7": {
    params: {};
  };
  "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05D7\u05E9\u05D1\u05D5\u05DF-\u05D0\u05D9\u05E0\u05E1\u05D8\u05D2\u05E8\u05DD": {
    params: {};
  };
  "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05D7\u05E9\u05D1\u05D5\u05DF-\u05D5\u05D5\u05D0\u05D8\u05E1\u05D0\u05E4": {
    params: {};
  };
  "/\u05D7\u05E9\u05D1\u05D5\u05DF-\u05E4\u05D9\u05D9\u05E1\u05D1\u05D5\u05E7-\u05DE\u05D5\u05E9\u05D1\u05EA": {
    params: {};
  };
  "/\u05D7\u05E9\u05D1\u05D5\u05DF-\u05D0\u05D9\u05E0\u05E1\u05D8\u05D2\u05E8\u05DD-\u05E0\u05E4\u05E8\u05E5": {
    params: {};
  };
  "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05DE\u05E0\u05D4\u05DC-\u05DE\u05D5\u05D3\u05E2\u05D5\u05EA": {
    params: {};
  };
  "/newsletter": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/testimonials": {
    params: {};
  };
  "/bms-sm": {
    params: {};
  };
  "/VSL-BMS": {
    params: {};
  };
  "/VSL-BMS-V2": {
    params: {};
  };
  "/\u05EA\u05D5\u05D3\u05D4-\u05E7\u05DC\u05D9\u05E1\u05D8": {
    params: {};
  };
  "/\u05EA\u05D5\u05D3\u05D4-\u05E8\u05DB\u05D9\u05E9\u05D4": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/en": {
    params: {};
  };
  "/en/privacy": {
    params: {};
  };
  "/en/press": {
    params: {};
  };
  "/en/articles": {
    params: {};
  };
  "/en/articles/:slug": {
    params: {
      "slug": string;
    };
  };
  "/en/facebook-account-recovery": {
    params: {};
  };
  "/en/instagram-account-recovery": {
    params: {};
  };
  "/en/whatsapp-account-recovery": {
    params: {};
  };
  "/en/facebook-account-disabled": {
    params: {};
  };
  "/en/instagram-account-hacked": {
    params: {};
  };
  "/en/ads-manager-recovery": {
    params: {};
  };
  "/en/newsletter": {
    params: {};
  };
  "/en/faq": {
    params: {};
  };
  "/en/testimonials": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/privacy" | "/press" | "/articles" | "/articles/:slug" | "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05D7\u05E9\u05D1\u05D5\u05DF-\u05E4\u05D9\u05D9\u05E1\u05D1\u05D5\u05E7" | "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05D7\u05E9\u05D1\u05D5\u05DF-\u05D0\u05D9\u05E0\u05E1\u05D8\u05D2\u05E8\u05DD" | "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05D7\u05E9\u05D1\u05D5\u05DF-\u05D5\u05D5\u05D0\u05D8\u05E1\u05D0\u05E4" | "/\u05D7\u05E9\u05D1\u05D5\u05DF-\u05E4\u05D9\u05D9\u05E1\u05D1\u05D5\u05E7-\u05DE\u05D5\u05E9\u05D1\u05EA" | "/\u05D7\u05E9\u05D1\u05D5\u05DF-\u05D0\u05D9\u05E0\u05E1\u05D8\u05D2\u05E8\u05DD-\u05E0\u05E4\u05E8\u05E5" | "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05DE\u05E0\u05D4\u05DC-\u05DE\u05D5\u05D3\u05E2\u05D5\u05EA" | "/newsletter" | "/faq" | "/testimonials" | "/bms-sm" | "/VSL-BMS" | "/VSL-BMS-V2" | "/\u05EA\u05D5\u05D3\u05D4-\u05E7\u05DC\u05D9\u05E1\u05D8" | "/\u05EA\u05D5\u05D3\u05D4-\u05E8\u05DB\u05D9\u05E9\u05D4" | "/dashboard" | "/en" | "/en/privacy" | "/en/press" | "/en/articles" | "/en/articles/:slug" | "/en/facebook-account-recovery" | "/en/instagram-account-recovery" | "/en/whatsapp-account-recovery" | "/en/facebook-account-disabled" | "/en/instagram-account-hacked" | "/en/ads-manager-recovery" | "/en/newsletter" | "/en/faq" | "/en/testimonials";
  };
  "./routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/privacy.jsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "./routes/press.jsx": {
    id: "routes/press";
    page: "/press";
  };
  "./routes/articles.jsx": {
    id: "routes/articles";
    page: "/articles";
  };
  "./routes/articles.$slug.jsx": {
    id: "routes/articles.$slug";
    page: "/articles/:slug";
  };
  "./routes/facebook-recovery.jsx": {
    id: "routes/facebook-recovery";
    page: "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05D7\u05E9\u05D1\u05D5\u05DF-\u05E4\u05D9\u05D9\u05E1\u05D1\u05D5\u05E7";
  };
  "./routes/instagram-recovery.jsx": {
    id: "routes/instagram-recovery";
    page: "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05D7\u05E9\u05D1\u05D5\u05DF-\u05D0\u05D9\u05E0\u05E1\u05D8\u05D2\u05E8\u05DD";
  };
  "./routes/whatsapp-recovery.jsx": {
    id: "routes/whatsapp-recovery";
    page: "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05D7\u05E9\u05D1\u05D5\u05DF-\u05D5\u05D5\u05D0\u05D8\u05E1\u05D0\u05E4";
  };
  "./routes/facebook-disabled.jsx": {
    id: "routes/facebook-disabled";
    page: "/\u05D7\u05E9\u05D1\u05D5\u05DF-\u05E4\u05D9\u05D9\u05E1\u05D1\u05D5\u05E7-\u05DE\u05D5\u05E9\u05D1\u05EA";
  };
  "./routes/instagram-hacked.jsx": {
    id: "routes/instagram-hacked";
    page: "/\u05D7\u05E9\u05D1\u05D5\u05DF-\u05D0\u05D9\u05E0\u05E1\u05D8\u05D2\u05E8\u05DD-\u05E0\u05E4\u05E8\u05E5";
  };
  "./routes/ads-manager.jsx": {
    id: "routes/ads-manager";
    page: "/\u05E9\u05D7\u05D6\u05D5\u05E8-\u05DE\u05E0\u05D4\u05DC-\u05DE\u05D5\u05D3\u05E2\u05D5\u05EA";
  };
  "./routes/newsletter.jsx": {
    id: "routes/newsletter";
    page: "/newsletter";
  };
  "./routes/faq.jsx": {
    id: "routes/faq";
    page: "/faq";
  };
  "./routes/testimonials.jsx": {
    id: "routes/testimonials";
    page: "/testimonials";
  };
  "./routes/bms-sm.jsx": {
    id: "routes/bms-sm";
    page: "/bms-sm";
  };
  "./routes/vsl-bms.jsx": {
    id: "routes/vsl-bms";
    page: "/VSL-BMS";
  };
  "./routes/vsl-bms-v2.jsx": {
    id: "routes/vsl-bms-v2";
    page: "/VSL-BMS-V2";
  };
  "./routes/thank-you-lead.jsx": {
    id: "routes/thank-you-lead";
    page: "/\u05EA\u05D5\u05D3\u05D4-\u05E7\u05DC\u05D9\u05E1\u05D8";
  };
  "./routes/thank-you-purchase.jsx": {
    id: "routes/thank-you-purchase";
    page: "/\u05EA\u05D5\u05D3\u05D4-\u05E8\u05DB\u05D9\u05E9\u05D4";
  };
  "./routes/dashboard.jsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "./routes/en.home.jsx": {
    id: "routes/en.home";
    page: "/en";
  };
  "./routes/en.privacy.jsx": {
    id: "routes/en.privacy";
    page: "/en/privacy";
  };
  "./routes/en.press.jsx": {
    id: "routes/en.press";
    page: "/en/press";
  };
  "./routes/en.articles.jsx": {
    id: "routes/en.articles";
    page: "/en/articles";
  };
  "./routes/en.articles.$slug.jsx": {
    id: "routes/en.articles.$slug";
    page: "/en/articles/:slug";
  };
  "./routes/en.facebook-recovery.jsx": {
    id: "routes/en.facebook-recovery";
    page: "/en/facebook-account-recovery";
  };
  "./routes/en.instagram-recovery.jsx": {
    id: "routes/en.instagram-recovery";
    page: "/en/instagram-account-recovery";
  };
  "./routes/en.whatsapp-recovery.jsx": {
    id: "routes/en.whatsapp-recovery";
    page: "/en/whatsapp-account-recovery";
  };
  "./routes/en.facebook-disabled.jsx": {
    id: "routes/en.facebook-disabled";
    page: "/en/facebook-account-disabled";
  };
  "./routes/en.instagram-hacked.jsx": {
    id: "routes/en.instagram-hacked";
    page: "/en/instagram-account-hacked";
  };
  "./routes/en.ads-manager.jsx": {
    id: "routes/en.ads-manager";
    page: "/en/ads-manager-recovery";
  };
  "./routes/en.newsletter.jsx": {
    id: "routes/en.newsletter";
    page: "/en/newsletter";
  };
  "./routes/en.faq.jsx": {
    id: "routes/en.faq";
    page: "/en/faq";
  };
  "./routes/en.testimonials.jsx": {
    id: "routes/en.testimonials";
    page: "/en/testimonials";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/home": typeof import("./app/./routes/home.jsx");
  "routes/privacy": typeof import("./app/./routes/privacy.jsx");
  "routes/press": typeof import("./app/./routes/press.jsx");
  "routes/articles": typeof import("./app/./routes/articles.jsx");
  "routes/articles.$slug": typeof import("./app/./routes/articles.$slug.jsx");
  "routes/facebook-recovery": typeof import("./app/./routes/facebook-recovery.jsx");
  "routes/instagram-recovery": typeof import("./app/./routes/instagram-recovery.jsx");
  "routes/whatsapp-recovery": typeof import("./app/./routes/whatsapp-recovery.jsx");
  "routes/facebook-disabled": typeof import("./app/./routes/facebook-disabled.jsx");
  "routes/instagram-hacked": typeof import("./app/./routes/instagram-hacked.jsx");
  "routes/ads-manager": typeof import("./app/./routes/ads-manager.jsx");
  "routes/newsletter": typeof import("./app/./routes/newsletter.jsx");
  "routes/faq": typeof import("./app/./routes/faq.jsx");
  "routes/testimonials": typeof import("./app/./routes/testimonials.jsx");
  "routes/bms-sm": typeof import("./app/./routes/bms-sm.jsx");
  "routes/vsl-bms": typeof import("./app/./routes/vsl-bms.jsx");
  "routes/vsl-bms-v2": typeof import("./app/./routes/vsl-bms-v2.jsx");
  "routes/thank-you-lead": typeof import("./app/./routes/thank-you-lead.jsx");
  "routes/thank-you-purchase": typeof import("./app/./routes/thank-you-purchase.jsx");
  "routes/dashboard": typeof import("./app/./routes/dashboard.jsx");
  "routes/en.home": typeof import("./app/./routes/en.home.jsx");
  "routes/en.privacy": typeof import("./app/./routes/en.privacy.jsx");
  "routes/en.press": typeof import("./app/./routes/en.press.jsx");
  "routes/en.articles": typeof import("./app/./routes/en.articles.jsx");
  "routes/en.articles.$slug": typeof import("./app/./routes/en.articles.$slug.jsx");
  "routes/en.facebook-recovery": typeof import("./app/./routes/en.facebook-recovery.jsx");
  "routes/en.instagram-recovery": typeof import("./app/./routes/en.instagram-recovery.jsx");
  "routes/en.whatsapp-recovery": typeof import("./app/./routes/en.whatsapp-recovery.jsx");
  "routes/en.facebook-disabled": typeof import("./app/./routes/en.facebook-disabled.jsx");
  "routes/en.instagram-hacked": typeof import("./app/./routes/en.instagram-hacked.jsx");
  "routes/en.ads-manager": typeof import("./app/./routes/en.ads-manager.jsx");
  "routes/en.newsletter": typeof import("./app/./routes/en.newsletter.jsx");
  "routes/en.faq": typeof import("./app/./routes/en.faq.jsx");
  "routes/en.testimonials": typeof import("./app/./routes/en.testimonials.jsx");
};